// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bivariate_hazards
DataFrame bivariate_hazards(DataFrame df, DataFrame data);
RcppExport SEXP _DaME_bivariate_hazards(SEXP dfSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(bivariate_hazards(df, data));
    return rcpp_result_gen;
END_RCPP
}
// trivariate_hazards
DataFrame trivariate_hazards(DataFrame df, DataFrame data);
RcppExport SEXP _DaME_trivariate_hazards(SEXP dfSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(trivariate_hazards(df, data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DaME_bivariate_hazards", (DL_FUNC) &_DaME_bivariate_hazards, 2},
    {"_DaME_trivariate_hazards", (DL_FUNC) &_DaME_trivariate_hazards, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DaME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
