# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bivariate_hazards <- function(df, data) {
    .Call('_DaME_bivariate_hazards', PACKAGE = 'DaME', df, data)
}

trivariate_hazards <- function(df, data) {
    .Call('_DaME_trivariate_hazards', PACKAGE = 'DaME', df, data)
}

